export enum FootballProductsCategory {
    FOOTBALL_SHOES = "FOOTBALL_SHOES",
    JERSEYS = "JERSEYS",
    SHORTS = "SHORTS",
    GOALKEEPER_GLOVES = "GOALKEEPER_GLOVES",
    TRAINING_KITS = "TRAINING_KITS",
    FOOTBALL_BALLS = "FOOTBALL_BALLS",
    SHIN_GUARDS = "SHIN_GUARDS",
    SOCKS = "SOCKS",
    WATER_BOTTLES = "WATER_BOTTLES",
    BACKPACKS = "BACKPACKS",
    CAPS = "CAPS",
    WHISTLES = "WHISTLES",
    NETS = "NETS",
    MEDICAL_KITS = "MEDICAL_KITS"
  }
  